module.exports = {
	FIELD_MAP: {
		Peralatan: ["Merek"],
		"Peralatan rumah tangga": ["Warna", "Label produk"],
		Kebun: ["Bahan", "Jenis Meja Luar Ruangan", "Bentuk", "Warna"],
		Perkakas: ["Merek", "Jenis Juicer", "Sumber Tenaga"],
		Mebel: ["Ukuran Tempat Tidur", "Jenis Tempat Tidur", "Warna", "Merek", "Bahan", "Ruangan"],
		"Video Game": ["Platform", "Genre Video Game", "Peringkat ESRB", "Merek"],
		"Buku, Film, & Musik": [],
		"Tas & Koper": ["Merek", "Warna", "Bahan Koper", "Bahan"],
		"Pakaian & Sepatu Wanita": ["Ukuran", "Warna", "Merek", "Bahan"],
		"Pakaian & Sepatu Pria": ["Ukuran", "Gaya Mantel", "Pas", "Merek"],
		"Perhiasan & Aksesori": ["Gaya Gelang", "Batu permata", "Merek", "Bahan"],
		"Kesehatan & Kecantikan": ["Jenis Rambut", "Jenis Kelamin"],
		"Kebutuhan Hewan Peliharaan": ["Merek", "Jenis Hewan Peliharaan", "Ukuran Pet", "Dimensi"],
		"Bayi & Anak-Anak": ["Merek", "Bahan", "Warna"],
		"Mainan & Game": ["Rentang Usia", "Karakter", "Merek"],
		"Elektronik & komputer": ["Merek", "Model", "Kondisi"],
		"Telepon seluler": ["Ponsel yang Kompatibel", "Bahan Watch Band", "Ukuran Watch Band", "Warna", "Penyimpanan", "Merek"],
		Sepeda: ["Jenis Sepeda", "Merek", "Ukuran Roda Sepeda", "Bahan", "Tipe Suspensi"],
		"Seni & Kerajinan": ["Merek", "Bahan"],
		"Olahraga & Outdoor": ["Merek", "Jenis Olahraga", "Bahan", "Warna"],
		"Komponen otomotif": ["Merek", "Nomor Suku Cadang"],
		"Alat Musik": ["Merek", "Tipe Instrumen"],
		"Barang Antik & Koleksi": ["Gaya Dekorasi", "Negara Asal", "Periode Waktu", "Bahan"],
		"Cuci Gudang": [],
		"Lain-lain": [],
		Kendaraan: [
			"Jenis kendaraan",
			"Tahun",
			"Merek",
			"Model",
			"Jarak Tempuh",
			"Tipe bodi",
			"Transmisi",
			"Jenis bahan bakar",
			"Warna eksterior",
			"Warna interior",
			"Kapasitas Penumpang",
			"Panjang (ft)",
			"Kondisi Kendaraan",
			"Status surat",
			"VIN",
		],
		"Mobil/Truk": [
			"Jenis kendaraan",
			"Tahun",
			"Merek",
			"Model",
			"Jarak Tempuh",
			"Tipe bodi",
			"Transmisi",
			"Jenis bahan bakar",
			"Warna eksterior",
			"Warna interior",
			"Kapasitas Penumpang",
			"Kondisi Kendaraan",
			"Status surat",
			"VIN",
		],
		"Sepeda Motor": [
			"Jenis kendaraan",
			"Tahun",
			"Merek",
			"Model",
			"Jarak Tempuh",
			"Transmisi",
			"Jenis bahan bakar",
			"Warna eksterior",
		],
		Properti: [
			"Rumah dijual atau disewakan",
			"Jenis properti",
			"Jumlah Kamar Tidur",
			"Jumlah Kamar Mandi",
			"Luas Bangunan",
			"Luas Tanah",
			"Alamat",
			"Fasilitas",
		],
	},

	FIELD_CONFIG: {
		"Jenis kendaraan": {
			type: "select",
			options: [
				"Mobil/Truk",
				"Sepeda Motor",
				"Powersport",
				"RV/Camper",
				"Trailer",
				"Perahu",
				"Komersial/Industri",
				"Lainnya",
			],
		},
		Tahun: {
			type: "select",
			options: Array.from({ length: 2026 - 1900 + 1 }, (_, i) => String(2026 - i)),
		},
		"Jarak Tempuh": { type: "number" },
		"Tipe bodi": {
			type: "select",
			options: [
				"Coupe",
				"Truk",
				"Sedan",
				"Hatchback",
				"SUV",
				"Convertible",
				"Wagon",
				"Mini-van",
				"Van",
				"Lainnya",
			],
		},
		"Jenis bahan bakar": {
			type: "select",
			options: [
				"Diesel",
				"Listrik",
				"Bensin",
				"Fleksibel",
				"Hybrid",
				"Plug-in Hybrid",
				"Lainnya",
			],
		},
		Transmisi: {
			type: "select",
			options: ["Otomatis", "Manual", "Lainnya"],
		},
		"Kondisi Kendaraan": {
			type: "select",
			options: ["Luar biasa baik", "Sangat baik", "Baik", "Cukup", "Buruk"],
		},
		"Kapasitas penyimpanan": {
			type: "select",
			options: [
				"8 GB",
				"16 GB",
				"32 GB",
				"64 GB",
				"128 GB",
				"256 GB",
				"512 GB",
				"1 TB",
				"2 TB",
				"Lainnya",
			],
		},
		RAM: {
			type: "select",
			options: [
				"1 GB",
				"2 GB",
				"3 GB",
				"4 GB",
				"6 GB",
				"8 GB",
				"12 GB",
				"16 GB",
				"32 GB",
				"Lainnya",
			],
		},
		"Sistem operasi": {
			type: "select",
			options: ["Android", "iOS", "Lainnya"],
		},
		"Ukuran layar": {
			type: "select",
			options: [
				'4"',
				'5"',
				'6"',
				'7"',
				'8"',
				'10"',
				'12"',
				'14"',
				'15"',
				'17"',
				"Lainnya",
			],
		},
		"Tipe mebel": {
			type: "select",
			options: [
				"Meja",
				"Kursi",
				"Sofa",
				"Tempat Tidur",
				"Kasur",
				"Lemari",
				"Rak",
				"Lainnya",
			],
		},
		"Tipe Sepeda": {
			type: "select",
			options: [
				"Gunung (MTB)",
				"Balap (Road)",
				"Lipat",
				"Hybrid",
				"BMX",
				"Lainnya",
			],
		},
		"Ukuran roda": {
			type: "select",
			options: ['20"', '24"', '26"', '27.5"', '29"', "700c", "Lainnya"],
		},
		"Bahan rangka": {
			type: "select",
			options: ["Aluminium", "Karbon", "Baja", "Titanium", "Lainnya"],
		},
		Bahan: {
			type: "select",
			options: [
				"Kayu",
				"Logam",
				"Plastik",
				"Kaca",
				"Rotan",
				"Kain",
				"Kulit",
				"Lainnya",
			],
		},
		Warna: { type: "text" },
		"Warna eksterior": {
			type: "select",
			options: [
				"Hitam",
				"Putih",
				"Silver",
				"Abu-abu",
				"Merah",
				"Biru",
				"Hijau",
				"Kuning",
				"Cokelat",
				"Emas",
				"Lainnya",
			],
		},
		"Warna interior": {
			type: "select",
			options: [
				"Hitam",
				"Putih",
				"Silver",
				"Abu-abu",
				"Merah",
				"Biru",
				"Hijau",
				"Kuning",
				"Cokelat",
				"Emas",
				"Lainnya",
			],
		},
		"Tipe Properti": {
			type: "select",
			options: ["Rumah", "Apartemen", "Tanah", "Ruko", "Kantor", "Lainnya"],
		},
		Platform: {
			type: "select",
			options: [
				"PS5",
				"PS4",
				"PS3",
				"Xbox Series X",
				"Xbox One",
				"Nintendo Switch",
				"PC",
				"Lainnya",
			],
		},
		VIN: { type: "text" },
		"Status surat": {
			type: "select",
			options: ["Sertifikat Bersih", "Rebuilt", "Salvage", "Lainnya"],
		},
		Operator: {
			type: "select",
			options: ["Unlocked", "Telkomsel", "Indosat", "XL", "Smartfren", "Lainnya"],
		},
		"Ukuran kasur": {
			type: "select",
			options: ["King", "Queen", "Double", "Single", "Super Single", "Lainnya"],
		},
		"Tipe kasur": {
			type: "select",
			options: ["Springbed", "Busa", "Lateks", "Dipan", "Lainnya"],
		},
		"Bahan Watch Band": {
			type: "select",
			options: [
				"Aluminium",
				"Karet",
				"Kulit",
				"Logam",
				"Nilon",
				"Silikon",
				"Stainless Steel",
				"Lainnya",
			],
		},
		"Ukuran Watch Band": {
			type: "select",
			options: [
				"38mm",
				"40mm",
				"41mm",
				"42mm",
				"44mm",
				"45mm",
				"49mm",
				"Lainnya",
			],
		},
		"Jumlah Kamar Tidur": {
			type: "select",
			options: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10+"],
		},
		"Jumlah Kamar Mandi": {
			type: "select",
			options: ["1", "2", "3", "4", "5+"],
		},
		"Rumah dijual atau disewakan": {
			type: "select",
			options: ["Dijual", "Disewakan"],
		},
		"Jenis properti": {
			type: "select",
			options: ["Rumah", "Apartemen", "Townhouse", "Lainnya"],
		},
		"Genre Video Game": { type: "text" },
		"Peringkat ESRB": { type: "text" },
		"Label produk": { type: "text" },
		"Tipe Meja Outdoor": { type: "text" },
		Bentuk: { type: "text" },
		"Tipe Juicer": { type: "text" },
		"Ponsel yang Kompatibel": { type: "text" },
		"Batu Permata": { type: "text" },
		"Jenis rambut": { type: "text" },
		Gender: { type: "text" },
		"Jenis Hewan": { type: "text" },
		"Ukuran Hewan": { type: "text" },
		Dimensi: { type: "text" },
		"Bahan tali jam": { type: "text" },
		"Ukuran tali jam": { type: "text" },
		"Ukuran roda sepeda": { type: "text" },
		"Rentang Usia": { type: "text" },
		Tipe: { type: "text" },
		Karakter: { type: "text" },
		Ukuran: { type: "text" },
		Pola: { type: "text" },
		Pas: { type: "text" },
		"Tinggi hak": { type: "text" },
		"Luas Tanah": { type: "number" },
		"Luas Bangunan": { type: "number" },
		"Nama model": { type: "text" },
		Merek: { type: "text" },
		Model: { type: "text" },
		Alamat: { type: "text" },
		"Bahan Koper": { type: "text" },
		"Gaya Mantel": { type: "text" },
		Fasilitas: { type: "text" },
		"Ukuran Tempat Tidur": {
			type: "select",
			options: ["King", "Queen", "Double", "Single", "Super Single", "Lainnya"],
		},
		"Jenis Tempat Tidur": {
			type: "select",
			options: ["Springbed", "Busa", "Lateks", "Dipan", "Lainnya"],
		},
		"Jenis Meja Luar Ruangan": { type: "text" },
		"Jenis Juicer": { type: "text" },
		"Gaya Gelang": { type: "text" },
		"Batu permata": { type: "text" },
		"Jenis Rambut": { type: "text" },
		"Jenis Kelamin": { type: "text" },
		"Jenis Hewan Peliharaan": { type: "text" },
		"Ukuran Pet": { type: "text" },
		"Jenis Sepeda": {
			type: "select",
			options: [
				"Gunung (MTB)",
				"Balap (Road)",
				"Lipat",
				"Hybrid",
				"BMX",
				"Lainnya",
			],
		},
		"Ukuran Roda Sepeda": {
			type: "select",
			options: ['20"', '24"', '26"', '27.5"', '29"', "700c", "Lainnya"],
		},
		"Gaya Dekorasi": { type: "text" },
		"Negara Asal": { type: "text" },
		"Periode Waktu": { type: "text" },
	}
};
